### ISSUE TITLE
Tutorial on https://hub.qovery.com/docs/using-qovery/configuration/clusters/#how-do-i-set-up-a-cluster failed

### ISSUE THREAD

**Issue by laleshii** [Qovery/documentation#173]
The tutorial on:

https://hub.qovery.com/docs/using-qovery/configuration/clusters/#how-do-i-set-up-a-cluster

Here's what went wrong:

> CONTAINER_REGISTRY_INVALID_INFORMATION
> CreateError - Invalid container registry information

**Comment by alecarrano** [comment]
Hi @laleshii ,

this seems to be a cloud provider credential issue (we are improving the error message). Please double-check the credentials you have set on Qovery side to access your cloud provider account.

If you need more help, please open a thread on our forum https://discuss.qovery.com/
