### ISSUE TITLE
Tutorial on https://hub.qovery.com/docs/using-qovery/integration/webhook/ failed

### ISSUE THREAD

**Issue by bos79** [Qovery/documentation#175]
The tutorial on:

https://hub.qovery.com/docs/using-qovery/integration/webhook/

Here's what went wrong:

**Comment by alecarrano** [comment]
Hi @bos79 ,

your comment is missing part of the text. what did not work?

if you need more assistance on the webhooks behaviour, please open a thread on our forum https://discuss.qovery.com/
