### ISSUE TITLE
Tutorial on https://docs.qovery.com/guides/getting-started/deploy-your-first-application/ failed

### ISSUE THREAD

**Issue by patarapolw** [Qovery/documentation#2]
The tutorial on:

https://docs.qovery.com/guides/getting-started/deploy-your-first-application/

Here's what went wrong:

```sh
patarapolw@pacharapol-elem:~/projects/simple-example-node$ qovery status
  BRANCH NAME | STATUS | ENDPOINTS | APPLICATIONS | DATABASES |   
              |        |           |              |           |   

  APPLICATION NAME | STATUS | DATABASES  
                   |        |            

  DATABASE NAME | STATUS | TYPE | VERSION | ENDPOINT | PORT | USERNAME | PASSWORD | APPLICATIONS  
                |        |      |         |          |      |          |          |               

patarapolw@pacharapol-elem:~/projects/simple-example-node$ qovery run
ERROR:   The project does not exist. Are you well authenticated with the right user? Do 'qovery auth' to be sure
```

This is exactly the [hello-world](https://github.com/patarapolw/simple-example-node) forked.

**Comment by evoxmusic** [comment]
Hi @patarapolw, did you give access to the Qovery github app?

**Comment by patarapolw** [comment]
Yes, also with SSH setup as well (otherwise I cannot clone git@)

**Comment by pjeziorowski** [comment]
Hello @patarapolw, thanks for the report.

To make sure that Qovery has access to this particular repository, you can go to:

https://github.com/settings/installations

Click "Configure" next to Qovery:

<img width="776" alt="image" src="https://user-images.githubusercontent.com/44570539/80306090-63bd2700-87c1-11ea-9f26-e1e630f46d3a.png">

And you'll see the list of selected repositories (maybe this one is not there?). You can also allow us to access all repositories, so all future repos you create will work fine without any additional actions.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/44570539/80306077-4e47fd00-87c1-11ea-9132-dff10790b663.png">

I just forked this repo (from the tutorial) and it deployed successfully for me. It's possible that it's repository acccess issues in your case.

**Comment by evoxmusic** [comment]
Please reopen this issue if it is still the case. Thanks
