### ISSUE TITLE
Tutorial on https://hub.qovery.com/docs/using-qovery/configuration/clusters/#generating-an-ssh-key-for-your-cluster failed

### ISSUE THREAD

**Issue by n523138** [Qovery/documentation#296]
The tutorial on:

https://hub.qovery.com/docs/using-qovery/configuration/clusters/#generating-an-ssh-key-for-your-cluster

Here's what went wrong:

For the sakes of completeness, it would be nice to add an extra step with instructions on how to copy the public key just generated. Example:

cat ~/.ssh/id_rsa.pub | pbcopy

By the way, when creating the cluster for the first time (new account), there's a link to this documentation (apparently) on top of the page but it does not work.

**Comment by acarranoqovery** [comment]
thanks @n523138 for reporting this. I've submitted a PR to fix the links on the console. The documentation will be fixed with this PR https://github.com/Qovery/documentation/pull/297
