### ISSUE TITLE
Tutorial on https://hub.qovery.com/docs/using-qovery/configuration/database/ failed

### ISSUE THREAD

**Issue by NewAlexandria** [Qovery/documentation#343]
The tutorial on:

https://hub.qovery.com/docs/using-qovery/configuration/database/

Here's what went wrong:

the Credential info is no longer where the screenshot shows.  Either you moved it, or there's a bug

<img width="404" alt="qovery bug report" src="https://github.com/Qovery/documentation/assets/87758/2a0e2aa7-be54-4160-a851-f23e5bb06ee5">

**Comment by acarranoqovery** [comment]
Hi @NewAlexandria ,

it's indeed a bug on our interface that we are currently fixing

**Comment by ctjhoa** [comment]
@NewAlexandria This should be fixed with https://github.com/Qovery/console/releases/tag/v1.60.0

![2023-10-25-111111_563x806_scrot](https://github.com/Qovery/documentation/assets/1716173/313736d5-fcb4-4cd0-ae7d-b25c006f6dfd)
