### ISSUE TITLE
Tutorial `Setup VPC peering on AWS with Qovery` Step 5 issue typo opposite behaviour

### ISSUE THREAD

**Issue by annececiledunand** [Qovery/documentation#445]
The tutorial on:

https://hub.qovery.com/guides/tutorial/aws-vpc-peering-with-qovery/
Step 5

Here's what went wrong:

Old :
In the AWS console of your **non Qovery VPC,** go to VPC > Route Tables. You can filter the list using the IDs you noted at step 1 to find the routing table for your existing VPC.

New :
In the AWS console of your **Qovery VPC,** go to VPC > Route Tables. You can filter the list using the IDs you noted at step 1 to find the routing table for your existing VPC.

<img width="1214" alt="Capture d’écran 2024-07-11 à 17 12 57" src="https://github.com/Qovery/documentation/assets/44811434/9ceff39d-cfda-4f8f-8a7e-a50fe0ad740d">

**Comment by jul-dan** [comment]
Thanks @annececiledunand. The tutorial has been updated!
