### ISSUE TITLE
Tutorial on https://hub.qovery.com/guides/getting-started/deploy-your-first-application failed

### ISSUE THREAD

**Issue by askfriends** [Qovery/documentation#73]
The tutorial on:

https://hub.qovery.com/guides/getting-started/deploy-your-first-application

Here's what went wrong:

User interface is chandged, How to create an organization with "Community" plan?

**Comment by alecarrano** [comment]
Hi @askfriends ,

Community plan doesn't exist anymore and the documentation has been updated
